name: Tagged release

on:
  push:
    tags:
      - "v*"

jobs:
  gh_tagged_release:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Tests to succeed
        uses: fountainhead/action-wait-for-check@v1
        id: wait-for-test
        with:
          token: ${{ secrets.PA_TOKEN }}
          checkName: Test
          ref: ${{ github.sha }}
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.8.2
      - name: Install redtape with Poetry
        run: poetry install
      - name: Build redtape with Poetry
        run: poetry build
      - name: Get latest tag
        id: latest
        uses: WyriHaximus/github-action-get-previous-tag@v1
      - name: Release new SemVer tag
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.PA_TOKEN }}"
          prerelease: false
          files: |
            dist/redtape_py-${{ steps.latest.outputs.tag }}.tar.gz
            dist/redtape_py-${{ steps.latest.outputs.tag }}-py2.py3-none-any.whl
        id: automatic_releases
